version: '3.8'

services:
  go_app:
    build: ./
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"
    networks:
      - go_redis

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PORT=6379
    networks:
      - go_redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  go_redis:

volumes:
  redis_data: