version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    image: jamalshahverdiev/game:0.0.2
    depends_on:
      - redis
    environment:
      REDIS_ADDR: "redis:6379"
    ports:
      - "8080:8080"
