apiVersion: v1
kind: Pod
metadata:
  name: redis-client
  namespace: goapp
spec:
  containers:
  - name: redis-cli-container
    image: redis
    command: ["/bin/sh", "-c"]
    args: ["while true; do sleep 30; done"] # Keeps the container running indefinitely
  restartPolicy: Always
