{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default .Values.secret.name (trunc 15 .Values.global.appName) }}
type: Opaque
data:
{{- range .Values.secret.keys }}
  {{ .key }}: {{ .keyValue }}
{{- end }}
{{- end }}