{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ default .Release.Name (trunc 15 .Values.global.appName) }}
  labels:
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames: 
      - {{ default .Release.Namespace }}
  selector:
    matchLabels: {{- include "common.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.global.appName }}
    path: /metrics
{{- end }}