apiVersion: batch/v1
kind: CronJob
metadata:
  name: goapp-exporter
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: goapp-exporter
            command: ["/bin/sh"]
            args: ["-c", "/opt/monitoring.sh"]
            image: alpine/curl:8.5.0
            volumeMounts:
            - name: monitoring
              mountPath: /opt/monitoring.sh
              subPath: monitoring.sh
              readOnly: false
            env:
            - name: GO_URL
              value: goapp:8080
          restartPolicy: Never
          volumes:
          - name: monitoring
            configMap:
              name: monitoring
              defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring
data:
  monitoring.sh: |
    #! /bin/sh

    availability=$(curl -X GET -s -o /dev/null -w "%{http_code}" "$GO_URL")
    if [ $availability -eq 200 ]; then
      echo "Application available"
      echo "goapp_availability 1" | curl --data-binary @- -s prometheus-prometheus-pushgateway:9091/metrics/job/goapp/instance/script-exporter   
    else
      echo "Application not available"
      echo "goapp_availability 0" | curl --data-binary @- -s prometheus-prometheus-pushgateway:9091/metrics/job/goapp/instance/script-exporter 
    fi

    input=$(curl -s "$GO_URL")
    current_time=$(echo $input | grep -o -E '[0-9]{2}:[0-9]{2}:[0-9]{2}')   
    count=0
    i=0
    while [ $i -le 5 ]; do
      new_input=$(curl -s "$GO_URL")
      new_current_time=$(echo $new_input | grep -o -E '[0-9]{2}:[0-9]{2}:[0-9]{2}')
      echo "Application current time: ${new_current_time}"
      if [ "$new_current_time" != "$current_time" ]; then
        count=$(( count + 1 ))
        current_time=$new_current_time
      fi
      i=$(( i + 1 ))
      sleep 1
    done

    if [ $count -eq 1 ]; then
      echo "goapp_tests 1" | curl --data-binary @- -s prometheus-prometheus-pushgateway:9091/metrics/job/goapp/instance/script-exporter
    else
      echo "goapp_tests 0" | curl --data-binary @- -s prometheus-prometheus-pushgateway:9091/metrics/job/goapp/instance/script-exporter
    fi