resources:
 limits:
   cpu: 2
   memory: 512Mi
 requests:
   cpu: 100m
   memory: 256Mi

configmapReload:
  prometheus:
    enabled: true

server:
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m

  # service:
  #   enabled: true
  #   type: LoadBalancer
  #   port: 80
  #   targetPort: 9090

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: "redis-exporter"
        scrape_interval: 15s
        static_configs:
          - targets: 
            - redis-exporter:9121
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - monitoring
        relabel_configs:
          - source_labels:
            - __meta_kubernetes_namespace
            action: replace
            target_label: namespace
          - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
            action: replace
            target_label: instance
      - job_name: "script-exporter"
        scrape_interval: 1m
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - monitoring
        relabel_configs:
          - source_labels:
            - __meta_kubernetes_namespace
            action: replace
            target_label: namespace
          - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
            action: replace
            target_label: instance

alertmanager:
    enabled: true

prometheus-node-exporter:
  enabled: false