resources:
 limits:
   cpu: 2
   memory: 512Mi
 requests:
   cpu: 100m
   memory: 256Mi

configmapReload:
  prometheus:
    enabled: true

server:
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m

  ingress:
    enabled: true
    annotations: {kubernetes.io/ingress.class: "nginx"}
    hosts: 
      - "prometheus.local"
    paths:
      - /

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: "redis-exporter"
        scrape_interval: 15s
        static_configs:
          - targets: 
            - prometheus-redis-exporter:9121
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - devops-test-task
        relabel_configs:
          - source_labels:
            - __meta_kubernetes_namespace
            action: replace
            target_label: namespace
          - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
            action: replace
            target_label: instance
      - job_name: "script-exporter"
        scrape_interval: 1m
        scrape_timeout: 30s
        static_configs:
        - targets:
          - script-exporter:9469


prometheus-node-exporter:
  enabled: false